Adding ex 2
kardaszb/HomeWork11 pull request #2
Opened 2020-05-15 07:36 UTC by kardaszb

2020-05-15 12:01 UTC, pawel-javastart requested changes

2020-05-15 12:01 UTC, pawel-javastart commented on src/wh11_2/MathOperations.java
> +    private static String stringConverter(int A, int B, String operator, int result){
nazwa metody powinna okeslac czynnosc : `convertToString`

2020-05-15 12:01 UTC, pawelkoperjavastart commented on src/wh11_2/MathOperations.java
> +    static void mathOperations(MathValues[] mathValues) {
nazwa metody powinna okeslac czynnosc : `writeMathOperationsTofile`

2020-05-15 12:01 UTC, pawelkoperjavastart commented on src/wh11_2/MathOperations.java
> +    private static int result(int A, int B, String operator) {
nazwa metody powinna okeslac czynnosc : `calculateResults`

2020-05-15 12:01 UTC, pawelkoperjavastart commented on src/wh11_2/FileOperations.java
> +    static void fileWriter(String fileName, String nextLine) {
nazwa metody powinna okeslac czynnosc : `writeToFile`

tak samo w metodach ponizszych

2020-05-16 05:06 UTC, kardaszb reviewed
Kkk

2020-05-19 22:04 UTC, merged